/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property block
 * @property name
 * @property partitionId
 * @property weight
 */
@JsonClass(generateAdapter = true)
data class CoursePartUpdateRequest(
    @Json(name = "block") @field:Json(name = "block") var block: Double,
    @Json(name = "partitionId") @field:Json(name = "partitionId") var partitionId: Long,
    @Json(name = "weight") @field:Json(name = "weight") var weight: Double,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null
)
