/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property notificationType
 */
@JsonClass(generateAdapter = true)
data class NotificationCreateRequest(
    @Json(name = "notificationType") @field:Json(name = "notificationType") var notificationType: NotificationCreateRequest.NotificationTypeEnum
) {
    /**
     * Values: USERWORKUPDATE, WORKUPDATE
     */
    @JsonClass(generateAdapter = false)
    enum class NotificationTypeEnum(val value: String) {
        @Json(name = "USERWORKUPDATE") USERWORKUPDATE("USERWORKUPDATE"),
        @Json(name = "WORKUPDATE") WORKUPDATE("WORKUPDATE")
    }
}
