/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property objectsIds
 * @property solutions
 */
@JsonClass(generateAdapter = true)
data class ObjectsWithSolutionsAddRequest(
    @Json(name = "objectsIds") @field:Json(name = "objectsIds") var objectsIds: List<Long>,
    @Json(name = "solutions") @field:Json(name = "solutions") var solutions: Map<String, String>
)
