/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property partitionIds
 * @property userParts
 */
@JsonClass(generateAdapter = true)
data class PartitionAddRequest(
    @Json(name = "partitionIds") @field:Json(name = "partitionIds") var partitionIds: List<Long>,
    @Json(name = "userParts") @field:Json(name = "userParts") var userParts: Map<String, Int>
)
