/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property group
 * @property id
 * @property name
 * @property users
 */
@JsonClass(generateAdapter = true)
data class Partition(
    @Json(name = "group") @field:Json(name = "group") var group: Group? = null,
    @Json(name = "id") @field:Json(name = "id") var id: Long? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "users") @field:Json(name = "users") var users: List<UserToPartition>? = null
)
