/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property page
 */
@JsonClass(generateAdapter = true)
data class SheetLinkData(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "page") @field:Json(name = "page") var page: String? = null
)
