/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property columns
 * @property sheetLink
 * @property usersRange
 */
@JsonClass(generateAdapter = true)
data class SheetInitData(
    @Json(name = "columns") @field:Json(name = "columns") var columns: List<MarksColumnData>? = null,
    @Json(name = "sheetLink") @field:Json(name = "sheetLink") var sheetLink: SheetLinkData? = null,
    @Json(name = "usersRange") @field:Json(name = "usersRange") var usersRange: UsersRangeData? = null
)
