/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property coursePart
 * @property id
 * @property roles
 * @property user
 */
@JsonClass(generateAdapter = true)
data class UserCoursePartRole(
    @Json(name = "coursePart") @field:Json(name = "coursePart") var coursePart: CoursePart? = null,
    @Json(name = "id") @field:Json(name = "id") var id: UserCoursePartRoleKey? = null,
    @Json(name = "roles") @field:Json(name = "roles") var roles: List<Role>? = null,
    @Json(name = "user") @field:Json(name = "user") var user: User? = null
)
