/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property group
 * @property id
 * @property roles
 * @property user
 */
@JsonClass(generateAdapter = true)
data class UserGroupRole(
    @Json(name = "group") @field:Json(name = "group") var group: Group,
    @Json(name = "id") @field:Json(name = "id") var id: UserGroupRoleKey,
    @Json(name = "roles") @field:Json(name = "roles") var roles: List<Role>,
    @Json(name = "user") @field:Json(name = "user") var user: User
)
