/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property id
 * @property mark
 * @property sendTime
 * @property solution
 * @property user
 * @property work
 */
@JsonClass(generateAdapter = true)
data class UserWork(
    @Json(name = "id") @field:Json(name = "id") var id: UserWorkKey? = null,
    @Json(name = "mark") @field:Json(name = "mark") var mark: Double? = null,
    @Json(name = "sendTime") @field:Json(name = "sendTime") var sendTime: ZonedDateTime? = null,
    @Json(name = "solution") @field:Json(name = "solution") var solution: String? = null,
    @Json(name = "user") @field:Json(name = "user") var user: User? = null,
    @Json(name = "work") @field:Json(name = "work") var work: Work? = null
)
