/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id
 * @property partition
 * @property user
 * @property userPart
 */
@JsonClass(generateAdapter = true)
data class UserToPartition(
    @Json(name = "id") @field:Json(name = "id") var id: UserToPartitionKey? = null,
    @Json(name = "partition") @field:Json(name = "partition") var partition: Partition? = null,
    @Json(name = "user") @field:Json(name = "user") var user: User? = null,
    @Json(name = "userPart") @field:Json(name = "userPart") var userPart: Int? = null
)
