/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property userIds
 * @property userRangeBegin
 */
@JsonClass(generateAdapter = true)
data class UsersRangeData(
    @Json(name = "userIds") @field:Json(name = "userIds") var userIds: List<Long>? = null,
    @Json(name = "userRangeBegin") @field:Json(name = "userRangeBegin") var userRangeBegin: Int? = null
)
