/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property block
 * @property date
 * @property description
 * @property name
 * @property weight
 */
@JsonClass(generateAdapter = true)
data class WorkUpdateRequest(
    @Json(name = "date") @field:Json(name = "date") var date: ZonedDateTime,
    @Json(name = "block") @field:Json(name = "block") var block: Double? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "weight") @field:Json(name = "weight") var weight: Double? = null
)
