/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property block
 * @property coursePartId
 * @property date
 * @property description
 * @property name
 * @property weight
 * @property workType
 */
@JsonClass(generateAdapter = true)
data class WorkCreateRequest(
    @Json(name = "block") @field:Json(name = "block") var block: Double,
    @Json(name = "coursePartId") @field:Json(name = "coursePartId") var coursePartId: Long,
    @Json(name = "description") @field:Json(name = "description") var description: String,
    @Json(name = "name") @field:Json(name = "name") var name: String,
    @Json(name = "weight") @field:Json(name = "weight") var weight: Double,
    @Json(name = "workType") @field:Json(name = "workType") var workType: WorkCreateRequest.WorkTypeEnum,
    @Json(name = "date") @field:Json(name = "date") var date: ZonedDateTime? = null
) {
    /**
     * Values: CONTROLWORK, HOMEWORK
     */
    @JsonClass(generateAdapter = false)
    enum class WorkTypeEnum(val value: String) {
        @Json(name = "CONTROLWORK") CONTROLWORK("CONTROLWORK"),
        @Json(name = "HOMEWORK") HOMEWORK("HOMEWORK")
    }
}
