version: "3"
services:
  hshelper:
    build: .
    restart: on-failure
    image: hshelper
    ports:
      - "1337:1337"
    networks:
      - hshelper-mysql
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    restart: always
    networks:
      - hshelper-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hshelper
      - MYSQL_DATABASE=hshelperdb

networks:
  hshelper-mysql: