/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.apis

import retrofit2.http.DELETE
import retrofit2.http.GET
import retrofit2.http.Headers
import retrofit2.http.POST
import retrofit2.http.PUT
import ru.hsHelper.androidApp.rest.codegen.models.Course
import ru.hsHelper.androidApp.rest.codegen.models.Group
import ru.hsHelper.androidApp.rest.codegen.models.GroupCreateRequest
import ru.hsHelper.androidApp.rest.codegen.models.GroupUpdateRequest
import ru.hsHelper.androidApp.rest.codegen.models.ObjectsWithRoleAddRequest
import ru.hsHelper.androidApp.rest.codegen.models.Partition
import ru.hsHelper.androidApp.rest.codegen.models.UserGroupRole

@JvmSuppressWildcards
interface GroupControllerApi {
    /**
     * addUsers
     * The endpoint is owned by server REST api service owner
     * @param groupId groupId (required)
     * @param objectsWithRoleAddRequest objectsWithRoleAddRequest (required)
     */
    @Headers(
        "X-Operation-ID: addUsersUsingPUT_2",
      "Content-Type: application/json"
    )
    @PUT("groups/{groupId}/users")
    suspend fun addUsersUsingPUT2(
        @retrofit2.http.Path("groupId") groupId: Long,
        @retrofit2.http.Body objectsWithRoleAddRequest: ObjectsWithRoleAddRequest
    ): Group
    /**
     * createGroup
     * The endpoint is owned by server REST api service owner
     * @param groupCreateRequest groupCreateRequest (required)
     */
    @Headers(
        "X-Operation-ID: createGroupUsingPOST",
      "Content-Type: application/json"
    )
    @POST("groups/")
    suspend fun createGroupUsingPOST(
        @retrofit2.http.Body groupCreateRequest: GroupCreateRequest
    ): Group
    /**
     * deleteGroup
     * The endpoint is owned by server REST api service owner
     * @param groupId groupId (required)
     */
    @Headers(
        "X-Operation-ID: deleteGroupUsingDELETE"
    )
    @DELETE("groups/{groupId}")
    suspend fun deleteGroupUsingDELETE(
        @retrofit2.http.Path("groupId") groupId: Long
    ): Unit
    /**
     * deleteUsers
     * The endpoint is owned by server REST api service owner
     * @param groupId groupId (required)
     * @param userIds userIds (required)
     */
    @Headers(
        "X-Operation-ID: deleteUsersUsingPOST_2",
      "Content-Type: application/json"
    )
    @POST("groups/{groupId}/users")
    suspend fun deleteUsersUsingPOST2(
        @retrofit2.http.Path("groupId") groupId: Long,
        @retrofit2.http.Body userIds: List<Long>
    ): Group
    /**
     * getAllCourses
     * The endpoint is owned by server REST api service owner
     * @param groupId groupId (required)
     */
    @Headers(
        "X-Operation-ID: getAllCoursesUsingGET_1"
    )
    @GET("groups/{groupId}/courses")
    suspend fun getAllCoursesUsingGET1(
        @retrofit2.http.Path("groupId") groupId: Long
    ): List<Course>
    /**
     * getAllGroups
     * The endpoint is owned by server REST api service owner
     */
    @Headers(
        "X-Operation-ID: getAllGroupsUsingGET"
    )
    @GET("groups/")
    suspend fun getAllGroupsUsingGET(): List<Group>
    /**
     * getAllPartitions
     * The endpoint is owned by server REST api service owner
     * @param groupId groupId (required)
     */
    @Headers(
        "X-Operation-ID: getAllPartitionsUsingGET"
    )
    @GET("groups/{groupId}/partitions")
    suspend fun getAllPartitionsUsingGET(
        @retrofit2.http.Path("groupId") groupId: Long
    ): List<Partition>
    /**
     * getAllUserGroupRoles
     * The endpoint is owned by server REST api service owner
     * @param groupId groupId (required)
     */
    @Headers(
        "X-Operation-ID: getAllUserGroupRolesUsingGET"
    )
    @GET("groups/{groupId}/users")
    suspend fun getAllUserGroupRolesUsingGET(
        @retrofit2.http.Path("groupId") groupId: Long
    ): List<UserGroupRole>
    /**
     * getGroup
     * The endpoint is owned by server REST api service owner
     * @param groupId groupId (required)
     */
    @Headers(
        "X-Operation-ID: getGroupUsingGET"
    )
    @GET("groups/{groupId}")
    suspend fun getGroupUsingGET(
        @retrofit2.http.Path("groupId") groupId: Long
    ): Group
    /**
     * getUserGroupRole
     * The endpoint is owned by server REST api service owner
     * @param groupId groupId (required)
     * @param userId userId (required)
     */
    @Headers(
        "X-Operation-ID: getUserGroupRoleUsingGET"
    )
    @GET("groups/{groupId}/users/{userId}")
    suspend fun getUserGroupRoleUsingGET(
        @retrofit2.http.Path("groupId") groupId: Long,
        @retrofit2.http.Path("userId") userId: Long
    ): UserGroupRole
    /**
     * updateGroup
     * The endpoint is owned by server REST api service owner
     * @param groupId groupId (required)
     * @param groupUpdateRequest groupUpdateRequest (required)
     */
    @Headers(
        "X-Operation-ID: updateGroupUsingPUT",
      "Content-Type: application/json"
    )
    @PUT("groups/{groupId}")
    suspend fun updateGroupUsingPUT(
        @retrofit2.http.Path("groupId") groupId: Long,
        @retrofit2.http.Body groupUpdateRequest: GroupUpdateRequest
    ): Group
}
