/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.apis

import retrofit2.http.Headers
import retrofit2.http.POST

@JvmSuppressWildcards
interface InitControllerApi {
    /**
     * initialize
     * The endpoint is owned by server REST api service owner
     */
    @Headers(
        "X-Operation-ID: initializeUsingPOST",
      "Content-Type: application/json"
    )
    @POST("init/")
    suspend fun initializeUsingPOST(): Unit
}
