/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Api Documentation
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package ru.hsHelper.androidApp.rest.codegen.apis

import retrofit2.http.Headers
import retrofit2.http.POST
import ru.hsHelper.androidApp.rest.codegen.models.SheetInitData

@JvmSuppressWildcards
interface SheetsControllerApi {
    /**
     * createSheet
     * The endpoint is owned by server REST api service owner
     * @param sheetInitData sheetInitData (required)
     */
    @Headers(
        "X-Operation-ID: createSheetUsingPOST",
      "Content-Type: application/json"
    )
    @POST("sheets/create")
    suspend fun createSheetUsingPOST(
        @retrofit2.http.Body sheetInitData: SheetInitData
    ): Long
    /**
     * updateSheet
     * The endpoint is owned by server REST api service owner
     * @param id id (required)
     */
    @Headers(
        "X-Operation-ID: updateSheetUsingPOST",
      "Content-Type: application/json"
    )
    @POST("sheets/update/{id}")
    suspend fun updateSheetUsingPOST(
        @retrofit2.http.Path("id") id: Long
    ): Unit
}
